server:
  port: 8761
  local: 127.0.0.1
  kafka_local: 127.0.0.1:9093

spring:
  application:
    name: discovery-api
  banner:
    location: banner.txt

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${server.local}:${server.port}/eureka