server:
  port: 8881
  local:
    ip: 127.0.0.1
    kafka: 127.0.0.1:9093

spring:
  application:
    name: stock-api
  jpa:
    show-sql: false
    hibernate.ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_versioned_data: true
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: jdbc:postgresql://${server.local.ip}:5432/payment_stock_db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 60000
      max-lifetime: 2000000
      connection-timeout: 60000
      pool-name: stockConnectionPool
  jackson:
    serialization:
      fail-on-empty-beans: false
  kafka:
    consumer:
      group-id: order-service-group-id
    bootstrap-servers: ${server.local.kafka}
  banner:
    location: banner.txt
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  cache:
    type: simple

eureka:
  client:
    service-url:
      defaultZone: http://${server.local.ip}:8761/eureka

couchbase:
  host: couchbase://${server.local.ip}
  username: Couchbase
  password: Couchbase
  bucket: PaymentBucket

elastic:
  host: 127.0.0.1:9200
  username: elastic
  password: elastic123
  cluster: elasticsearch
  index-stock: index_stock

springdoc:
  swagger-ui:
    tags-sorter: alpha
    display-request-duration: true

schedulers:
  outbox:
    enable: true
    initialDelayMillis: 3000
    fixedRate: 600000 #10dk

topics:
  notification:
    name: notification-queue
    partitions: 3
    replication: 1

cdn:
  configFile: classpath:CDN.json
  bucketName: springbootfirebase-cd166.appspot.com