server:
  port: 8085
  local: 127.0.0.1

spring:
  application:
    name: gateway-api
  config:
    import: predicate.yml

eureka:
  client:
    service-url:
      defaultZone: http://${server.local}:8761/eureka

springdoc:
  swagger-ui:
    tags-sorter: alpha

schedulers:
  outbox:
    enable: true
    initialDelayMillis: 3000
    fixedRate: 600000

api:
  url:
    users: http://localhost:8880/api/payment/users/auth/