server:
  port: 8088
  kafka_prod: 10.5.0.4:9092

spring:
  application:
    name: notification-api
  jackson:
    serialization:
      fail-on-empty-beans: false
  kafka:
    consumer:
      group-id: order-service-group-id
    bootstrap-servers: ${server.kafka_prod}
  banner:
    location: banner.txt

springdoc:
  swagger-ui:
    tags-sorter: alpha

schedulers:
  outbox:
    enable: true
    initialDelayMillis: 3000
    fixedRate: 600000

topics:
  notification:
    name: notification-queue
    partitions: 3
    replication: 1