server:
  port: 8088
  local: 127.0.0.1
  kafka_local: 127.0.0.1:9093

spring:
  application:
    name: notification-api
  jackson:
    serialization:
      fail-on-empty-beans: false
  kafka:
    consumer:
      group-id: order-service-group-id
    bootstrap-servers: ${server.kafka_local}
  banner:
    location: banner.txt

eureka:
  client:
    service-url:
      defaultZone: http://${server.local}:8761/eureka

springdoc:
  swagger-ui:
    tags-sorter: alpha

schedulers:
  outbox:
    enable: true
    initialDelayMillis: 3000
    fixedRate: 600000

topics:
  notification:
    name: notification-queue
    partitions: 3
    replication: 1

firebase:
  configFile: firebase.json