server:
  port: 8088
  local: 127.0.0.1
  kafka_local: 127.0.0.1:9093

spring:
  application:
    name: notification-api
  jpa:
    show-sql: false
    hibernate.ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: jdbc:postgresql://${server.local}:5432/payment_notification_db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 60000
      max-lifetime: 2000000
      connection-timeout: 60000
      pool-name: stockConnectionPool
  jackson:
    serialization:
      fail-on-empty-beans: false
  kafka:
    consumer:
      group-id: order-service-group-id
    bootstrap-servers: ${server.kafka_local}
  banner:
    location: banner.txt

logging:
  level:
    root: info
    org:
      springframework: info
      mybatis: error
  config: classpath:logback-spring.xml

eureka:
  client:
    service-url:
      defaultZone: http://${server.local}:8761/eureka

springdoc:
  swagger-ui:
    tags-sorter: alpha

schedulers:
  outbox:
    enable: true
    initialDelayMillis: 3000
    fixedRate: 600000

topics:
  notification:
    name: notification-queue
    partitions: 3
    replication: 1

firebase:
  configFile: firebase.json