pipeline {
	agent any
	tools {
	  maven 'maven'
	}
	stages {
		stage('Initialize'){
			steps {
               		sh '''
                  	echo "PATH = ${PATH}"
                  	echo "M2_HOME = ${M2_HOME}"
                  	'''
			}
		}
		stage('Build'){
			steps {
			echo "Java VERSION"
                	sh 'java -version'
                	echo "Maven VERSION"
			        sh 'mvn -version'
                	echo 'Building microservice-payment project...'
                	sh '''
                	cd microservice-payment/
                	mvn clean
                	mvn clean install -Pprod -DskipTests
                	'''
			}
		}
		stage('Deploy') {
			steps {
			echo "Building"
			}
		}
	}
}
