version: '3.3'

services:
  user:
    image: stock
    container_name: stock-api
    networks:
      nw_containers:
        ipv4_address: 10.5.0.8
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://10.5.0.2:5432/payment_stock_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=10.5.0.4:9092
    expose:
      - "8086"
    ports:
      - "8086:8086"
    command: -p 8086

networks:
  nw_containers:
    external:
      name: custom_bridge