version: '3.3'

services:
  stock:
    build:
      context: .
    image: stock
    container_name: stock-api
    networks:
      nw_containers:
        ipv4_address: 10.5.0.13
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://10.5.0.2:5432/payment_stock_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=10.5.0.4:9092
    expose:
      - "8881"
    ports:
      - "8881:8881"
    command: -p 8881

networks:
  nw_containers:
      name: custom_bridge
      external: true
