version: '3.3'

services:
  user:
    image: notification
    container_name: notification-api
    networks:
      nw_containers:
        ipv4_address: 10.5.0.13
    restart: always
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=10.5.0.4:9092
    expose:
      - "8088"
    ports:
      - "8088:8088"
    command: -p 8088

networks:
  nw_containers:
      name: custom_bridge
      external: true
