version: '3.3'

services:
  notification:
    build:
      context: .
    image: notification
    container_name: notification-api
    networks:
      nw_containers:
        ipv4_address: 10.5.0.14
    restart: always
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=10.5.0.4:9092
    expose:
      - "8882"
    ports:
      - "8882:8882"
    command: -p 8882

networks:
  nw_containers:
      name: custom_bridge
      external: true
