version: '3.3'

services:
  user:
    build:
      context: .
    image: user
    container_name: user-api
    networks:
      nw_containers:
        ipv4_address: 10.5.0.12
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://10.5.0.2:5432/payment_user_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=10.5.0.4:9092
    expose:
      - "8880"
    ports:
      - "8880:8880"
    command: -p 8880

networks:
  nw_containers:
      name: custom_bridge
      external: true
