version: '3.3'

services:
  user:
    image: report
    container_name: report-api
    networks:
      nw_containers:
        ipv4_address: 10.5.0.12
    restart: always
    expose:
      - "8883"
    ports:
      - "8883:8883"
    command: -p 8883

networks:
  nw_containers:
      name: custom_bridge
      external: true
