server:
  port: 8085
  prod:
    eureka: 10.5.0.10
    user-api: 10.5.0.12:8880

spring:
  application:
    name: gateway-api
  config:
    import: predicate.yml

eureka:
  client:
    service-url:
      defaultZone: http://${server.prod.eureka}:8761/eureka

springdoc:
  swagger-ui:
    tags-sorter: alpha

schedulers:
  outbox:
    enable: true
    initialDelayMillis: 3000
    fixedRate: 600000

api:
  url:
    users: http://${server.prod.user-api}/api/payment/users/auth/