server:
  port: 8085
  local: 127.0.0.1
  kafka_local: 127.0.0.1:9093

spring:
  application:
    name: gateway-api

eureka:
  client:
    service-url:
      defaultZone: http://${server.local}:8761/eureka

springdoc:
  swagger-ui:
    tags-sorter: alpha

schedulers:
  outbox:
    enable: true
    initialDelayMillis: 3000
    fixedRate: 600000
