spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*" # Allows requests from any origin
            allowedMethods: "GET,POST,PUT,DELETE" # Allows all HTTP methods (GET, POST, etc.)
            allowedHeaders: "*"
      httpclient:
        connect-timeout: 10000
        response-timeout: 7s
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user
          order: 0
          uri: lb://user-api
          predicates:
            - Host=**
            - Path=/api/payment/users/**
          filters:
            - JwtFilter

        - id: stock
          order: 1
          uri: lb://stock-api
          predicates:
            - Host=**
            - Path=/api/payment/stocks/**
          filters:
            - JwtFilter

        - id: payment
          order: 2
          uri: lb://payment-api
          predicates:
            - Host=**
            - Path=/api/order/**
          filters:
            - JwtFilter

        - id: notification
          order: 3
          uri: lb://notification-api
          predicates:
            - Host=**
            - Path=/api/payment/notification/**
          filters:
            - JwtFilter

        - id: report
          order: 4
          uri: lb://report-api
          predicates:
            - Host=**
            - Path=/api/payment/reports/**
          filters:
            - JwtFilter
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE