spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 7s
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: notification
          order: 0
          uri: lb://notification-api
          predicates:
            - Host=**
            - Path=/api/payment/notification/**
          filters:
            - NotifyFilter

