version: '3.3'

services:
  user:
    image: discovery
    container_name: discovery-api
    networks:
      nw_containers:
        ipv4_address: 10.5.0.1
    restart: always
    expose:
      - "8761"
    ports:
      - "8761:8761"
    command: -p 8761

networks:
  nw_containers:
      name: custom_bridge
      external: true
