server:
  port: 8884
  local:
    ip: 127.0.0.1

spring:
  application:
    name: payment-api
  jpa:
    show-sql: false
    hibernate.ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: jdbc:postgresql://${server.local.ip}:5432/payment_db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 60000
      max-lifetime: 2000000
      connection-timeout: 60000
      pool-name: paymentConnectionPool
  jackson:
    serialization:
      fail-on-empty-beans: false
  kafka:
    consumer:
      group-id: order-service-group-id
    bootstrap-servers: ${server.local.ip}:9093
  banner:
    location: banner.txt

eureka:
  client:
    service-url:
      defaultZone: http://${server.local.ip}:8761/eureka

springdoc:
  swagger-ui:
    tags-sorter: alpha
    display-request-duration: true

couchbase:
  host: couchbase://${server.local.ip}
  username: Couchbase
  password: Couchbase
  bucket: PaymentBucket

elastic:
  host: ${server.local.ip}:9200
  username: elastic
  password: elastic123
  cluster: elasticsearch
  index-stock: index_stock

schedulers:
  outbox:
    enable: true
    initialDelayMillis: 3000
    fixedRate: 600000

api:
  url:
    stock: stockServiceDev

topics:
  created:
    name: order-created
    partitions: 3
    replication: 1
  added:
    name: product-added
    partitions: 3
    replication: 1
  removed:
    name: product-added
    partitions: 3
    replication: 1
  payment:
    name: order-paid
    partitions: 3
    replication: 1
  cancelled:
    name: order-cancelled
    partitions: 3
    replication: 1
  submitted:
    name: order-submitted
    partitions: 3
    replication: 1
  completed:
    name: order-completed
    partitions: 3
    replication: 1

  retryTopic:
    name: retry-topic
    partitions: 3
    replication: 1

  deadLetterQueue:
    name: dead-letter-queue
    partitions: 3
    replication: 1

  notification:
    name: notification-queue
    partitions: 3
    replication: 1